name: Create Automated VM Version Bump PR
on:
  push:
    branches:
    - 'update-vm-image-**'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create pull request for new summary
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -m '[Automated] Update custom image version' -b xlight05:main
      env:
        GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
